modLoader = "javafml"
loaderVersion = "[38,)"
issueTrackerURL = "https://github.com/dzwdz/chat_heads/issues"
license = "MPL-2.0"

[[mods]]
modId = "chat_heads"
version = "${version}"
displayName = "Chat Heads"
authors = "dzwdz"

description = '''
See who are you chatting with!
This mod adds player heads next to their chat messages.
'''
logoFile = "icon.png"

[[dependencies.chat_heads]]
modId = "forge"
mandatory = true
versionRange = "[38.0.6,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.chat_heads]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.chat_heads]]
modId = "cloth_config"
mandatory = false
versionRange = "[6.0.0,)"
ordering = "NONE"
side = "CLIENT"

#[[dependencies.chat_heads]]
#modId = "architectury"
#mandatory = true
#versionRange = "[2.3.23,)"
#ordering = "AFTER"
#side = "BOTH"